version: '3.7'

volumes:
  pg_data:
  redis_data:

services:
  db:
    image: postgres:13.4
    env_file: .env
    container_name: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    env_file: .env
    container_name: ${REDIS_HOST}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    depends_on:
      - db
      - redis
    volumes:
      - .:/orders
    build:
      context: .
    ports:
      - "8000:8000"
    restart: on-failure
    command:
      - sh
      - -c
      - |
        python manage.py makemigrations backend --noinput
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - .:/orders
    command: celery -A orders.celery_app worker --loglevel=INFO